# -*- coding: utf-8 -*-
"""Mirror the outstanding video backlog onto an account that has idle quota.

Notebooks are Google-account-scoped, so an entry sitting in
video_queue_account2.json can ONLY be generated by account2. When the whole
remaining backlog happens to live on one account, the other two burn no quota
at all and the fleet runs at ~3 videos/day instead of ~9 — which is exactly the
state the arithmetic-laws + directed-numbers backlog was in.

This creates a notebook + uploads the chapter's source.md on the target
profile for every key that is still pending anywhere and not yet staged there.
Duplicating a key across accounts is safe: video_grinder.busy_elsewhere()
lets only one account generate it, and the first one done marks it done for
everyone.

Usage: python stage_backlog.py --profile account1 [--limit 8] [--dry-run]
"""
import argparse
import io
import json
import subprocess
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

HERE = Path(__file__).parent
ROOT = Path(r"C:\Users\yairk\OneDrive\שולחן העבודה\math-learning-system")

QUEUE_OF = {
    "account1": "video_queue_account1.json",
    "account2": "video_queue_account2.json",
    "account3": "video_queue_account3.json",
}

# course -> content dir holding chNN/source.md (mirror of video_grinder.targets)
COURSE_DIR = {
    "grade7-algebra": "grade7/algebra",
    "directed-numbers": "grade7/directed-numbers",
    "arithmetic-laws": "grade7/arithmetic-laws",
    "grade6-percents": "grade6/percents",
    "grade6-ratio-rate": "grade6/ratio-rate",
}

ap = argparse.ArgumentParser()
ap.add_argument("--profile", required=True, choices=sorted(QUEUE_OF))
ap.add_argument("--limit", type=int, default=8, help="max keys to stage this run")
ap.add_argument("--dry-run", action="store_true")
ARGS = ap.parse_args()

OUT_QUEUE = HERE / QUEUE_OF[ARGS.profile]


def nlm(*args):
    r = subprocess.run(
        ["notebooklm", "-p", ARGS.profile, *args],
        capture_output=True, text=True, encoding="utf-8",
        errors="replace", timeout=600,
    )
    out = (r.stdout or "") + (r.stderr or "")
    start = out.find("{")
    if start == -1:
        return {"raw": out}
    try:
        return json.loads(out[start:])
    except json.JSONDecodeError:
        return {"raw": out}


def source_path(entry):
    if entry.get("standalone_slug"):
        return None  # standalone courses are staged by hand, no chNN/source.md
    sub = COURSE_DIR.get(entry.get("course"))
    if not sub:
        sub = "grade5/simple-fractions" if entry.get("grade") == 5 else "grade6/fractions-decimals"
    return ROOT / "content" / sub / f"ch{entry['number']:02d}" / "source.md"


def collect():
    """Every key still needing a video, with a template entry to copy from."""
    done, pending = set(), {}
    for qname in QUEUE_OF.values():
        qf = HERE / qname
        if not qf.exists():
            continue
        for key, e in json.loads(qf.read_text(encoding="utf-8")).items():
            if e.get("status") == "done":
                done.add(key)
            else:
                pending.setdefault(key, e)
    return {k: e for k, e in pending.items() if k not in done}


def main():
    out_queue = json.loads(OUT_QUEUE.read_text(encoding="utf-8")) if OUT_QUEUE.exists() else {}
    todo = collect()
    staged = 0

    for key, entry in todo.items():
        if staged >= ARGS.limit:
            print(f"limit {ARGS.limit} reached — {len(todo) - staged} keys left for next run")
            break
        mine = out_queue.get(key, {})
        if mine.get("source_id"):
            print(f"{key}: already staged on {ARGS.profile} ({mine.get('status')})")
            continue
        src = source_path(entry)
        if src is None:
            print(f"{key}: standalone course — skipping (stage manually)")
            continue
        if not src.exists():
            print(f"{key}: MISSING source {src}")
            continue
        if ARGS.dry_run:
            print(f"{key}: would stage from {src.relative_to(ROOT)}")
            staged += 1
            continue

        if not mine.get("notebook_id"):
            res = nlm("create", f"סרטון: {entry['topic']}", "--json")
            nb = (res.get("notebook") or res).get("id")
            if not nb:
                print(f"{key}: FAILED create: {str(res)[:200]}")
                continue
            mine["notebook_id"] = nb
            print(f"{key}: notebook {nb}")
        res = nlm("source", "add", str(src), "--notebook", mine["notebook_id"], "--json")
        sid = (res.get("source") or res).get("id")
        if not sid:
            print(f"{key}: FAILED source add: {str(res)[:200]}")
            continue
        mine["source_id"] = sid
        mine.update({
            "number": entry["number"],
            "topic": entry["topic"],
            "output": entry["output"],
            "status": "staged",
            "course": entry.get("course"),
            "grade": entry.get("grade"),
        })
        out_queue[key] = mine
        OUT_QUEUE.write_text(json.dumps(out_queue, ensure_ascii=False, indent=1), encoding="utf-8")
        print(f"{key}: staged on {ARGS.profile} (source {sid})")
        staged += 1

    print(f"done — {staged} newly staged on {ARGS.profile}, queue: {OUT_QUEUE.name}")


if __name__ == "__main__":
    main()
